# Generated by Django 4.2.7 on 2023-11-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('disease', models.CharField(max_length=50, null=True)),
                ('doctor', models.CharField(max_length=50, null=True)),
                ('healthrecords', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
