# Generated by Django 4.2.7 on 2023-11-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosapp', '0002_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Prescription_upload',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='profile',
        ),
    ]
