# Generated by Django 4.2.7 on 2023-12-02 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hosapp', '0004_doctor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='saved_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
